// AUTO-GENERATED by scripts/node/build-tokenlists. Do not edit by hand.
// Run `cd scripts/node && npm run build-tokenlists` to regenerate after adding
// or removing tokenlist files under frontend/app/addresses/chain/.

export const GENERATED_CHAIN_PLATFORM_OVERRIDES: Record<number, unknown> = {
}
