// AUTO-GENERATED by scripts/node/build-tokenlists. Do not edit by hand.
// Run `cd scripts/node && npm run build-tokenlists` to regenerate after adding
// or removing tokenlist files under frontend/app/addresses/chain/.

import type { TokenList, TokenListRef } from './tokenlistCompose'

const ref = (id: string, list: unknown, priority = 50): TokenListRef => ({ id, priority, list: list as TokenList })

export const GENERATED_LIST_REGISTRY: Record<number, TokenListRef[]> = {
}
