#!/usr/bin/env bash
# Install a thin PATH wrapper so `cartographer` works from any cwd.
# Does NOT edit shell rc files — prints PATH instructions only.
#
# Note: the marketplace CLI resolves relative --root/--out paths against
# process.cwd, and the wrapper must `bun run --cwd "$MARKETPLACE" …`.
# Therefore this wrapper absolutizes path flags against the caller's PWD
# before exec so `cartographer index --root .` works from any directory.
set -euo pipefail

WRAPPER_DIR="${HOME}/bin"
WRAPPER_PATH="${WRAPPER_DIR}/cartographer"

# Marketplace discovery (PRD §0.7.2): env → default Claude plugins path
if [[ -n "${CARTOGRAPHER_MARKETPLACE:-}" ]]; then
  MARKETPLACE="${CARTOGRAPHER_MARKETPLACE}"
elif [[ -d "${HOME}/.claude/plugins/marketplaces/cartographer-marketplace" ]]; then
  MARKETPLACE="${HOME}/.claude/plugins/marketplaces/cartographer-marketplace"
else
  cat >&2 <<'EOF'
error: cartographer marketplace not found.

Set CARTOGRAPHER_MARKETPLACE to the marketplace root, or install the Claude plugin at:
  ~/.claude/plugins/marketplaces/cartographer-marketplace

Expected CLI entry: <marketplace>/src/cli/index.ts
EOF
  exit 1
fi

CLI_ENTRY="${MARKETPLACE}/src/cli/index.ts"
if [[ ! -f "${CLI_ENTRY}" ]]; then
  echo "error: marketplace CLI missing at ${CLI_ENTRY}" >&2
  exit 1
fi

if ! command -v bun >/dev/null 2>&1; then
  cat >&2 <<'EOF'
error: bun is required but not on PATH.

Install Bun: https://bun.sh
Then re-run: ./scripts/install-cartographer.sh
EOF
  exit 1
fi

mkdir -p "${WRAPPER_DIR}"

# Embed absolute marketplace path so the wrapper is self-contained after install.
cat > "${WRAPPER_PATH}" <<EOF
#!/usr/bin/env bash
# Auto-generated by scripts/install-cartographer.sh — do not hand-edit.
set -euo pipefail

CARTOGRAPHER_MARKETPLACE="\${CARTOGRAPHER_MARKETPLACE:-${MARKETPLACE}}"
if [[ ! -f "\${CARTOGRAPHER_MARKETPLACE}/src/cli/index.ts" ]]; then
  echo "error: cartographer marketplace not found at \${CARTOGRAPHER_MARKETPLACE}" >&2
  exit 1
fi
if ! command -v bun >/dev/null 2>&1; then
  echo "error: bun is required but not on PATH" >&2
  exit 1
fi

# Bun --cwd switches process.cwd to the marketplace; absolutize path flags
# against the caller's working directory so relative --root/--out work.
CALLER_PWD="\$(pwd -P 2>/dev/null || pwd)"

abspath() {
  local p="\$1"
  if [[ -z "\$p" ]]; then
    printf '%s' "\$p"
    return
  fi
  case "\$p" in
    /*) printf '%s' "\$p" ;;
    *)  printf '%s/%s' "\$CALLER_PWD" "\$p" ;;
  esac
}

# Flags whose values are filesystem paths for cartographer subcommands.
PATH_FLAGS="root out path map left right trace ledger"

is_path_flag() {
  local name="\$1"
  for f in \$PATH_FLAGS; do
    if [[ "\$f" == "\$name" ]]; then
      return 0
    fi
  done
  return 1
}

args=()
while [[ \$# -gt 0 ]]; do
  case "\$1" in
    --*=*)
      flag="\${1%%=*}"
      val="\${1#*=}"
      name="\${flag#--}"
      if is_path_flag "\$name"; then
        args+=("\${flag}=\$(abspath "\$val")")
      else
        args+=("\$1")
      fi
      shift
      ;;
    --*)
      name="\${1#--}"
      if is_path_flag "\$name" && [[ \$# -ge 2 ]]; then
        args+=("\$1" "\$(abspath "\$2")")
        shift 2
      else
        args+=("\$1")
        shift
      fi
      ;;
    *)
      args+=("\$1")
      shift
      ;;
  esac
done

exec bun run --cwd "\${CARTOGRAPHER_MARKETPLACE}" src/cli/index.ts "\${args[@]}"
EOF

chmod +x "${WRAPPER_PATH}"

echo "Installed: ${WRAPPER_PATH}"
echo "Marketplace: ${MARKETPLACE}"
echo
echo "If 'command -v cartographer' fails, add to your shell PATH for this session:"
echo "  export PATH=\"\$HOME/bin:\$PATH\""
echo
echo "Verify:"
echo "  export PATH=\"\$HOME/bin:\$PATH\""
echo "  command -v cartographer"
echo "  ( cd /tmp && cartographer --help )"

# Ensure marketplace deps once (best-effort; fail if install fails)
if [[ -f "${MARKETPLACE}/package.json" ]]; then
  if [[ ! -d "${MARKETPLACE}/node_modules" ]]; then
    echo
    echo "Installing marketplace dependencies (bun install)..."
    ( cd "${MARKETPLACE}" && bun install )
  fi
fi

echo
echo "Done."
