import {
  CHAIN_ID_BASE_SEPOLIA,
  CHAIN_ID_ROBINHOOD,
  CHAIN_ID_ROBINHOOD_TESTNET,
  CHAIN_ID_SEPOLIA,
  getArtifactBundle,
  type ArtifactBundle,
  type CanonicalArtifactChainId,
  type DeploymentEnvironment,
} from './addresses'

// Chain-keyed platform overrides. The map is generated by the tokenlist
// aggregator (`cd scripts/node && npm run build-tokenlists`) from every
// frontend/packages/protocol/src/addresses/chain/<id>/platform.json it finds on disk. Latest
// deploy to a chain populates these files; they win over the env-keyed
// ARTIFACT_REGISTRY.platform when present.
import { GENERATED_CHAIN_PLATFORM_OVERRIDES } from './chainPlatformOverrides.generated'

const CHAIN_PLATFORM_OVERRIDES: Record<number, unknown> = GENERATED_CHAIN_PLATFORM_OVERRIDES

export {
  CHAIN_ID_BASE_SEPOLIA,
  CHAIN_ID_ROBINHOOD,
  CHAIN_ID_ROBINHOOD_TESTNET,
  CHAIN_ID_SEPOLIA,
  getArtifactBundle,
  type ArtifactBundle,
  type CanonicalArtifactChainId,
  type DeploymentEnvironment,
}

export const CHAIN_ID_ANVIL = 31337
export const CHAIN_ID_LOCALHOST = 1337
export const CHAIN_ID_BASE = 8453

function isLocalSepoliaEnvironment(environment: DeploymentEnvironment): boolean {
  return environment === 'supersim_sepolia' || environment === 'local_testing'
}

let defaultDeploymentEnvironment: DeploymentEnvironment =
  (process.env.NEXT_PUBLIC_DEFAULT_DEPLOYMENT_ENVIRONMENT as DeploymentEnvironment | undefined) ?? 'supersim_sepolia'

export type AddressArtifacts = ArtifactBundle

export function setDefaultDeploymentEnvironment(environment: DeploymentEnvironment) {
  defaultDeploymentEnvironment = environment
}

export function getDefaultDeploymentEnvironment(): DeploymentEnvironment {
  return defaultDeploymentEnvironment
}

export function resolveArtifactsChainId(
  chainId: number,
  environment: DeploymentEnvironment = defaultDeploymentEnvironment,
  preferredCanonicalChainId?: CanonicalArtifactChainId
): CanonicalArtifactChainId | null {
  // Robinhood mainnet (4663) and testnet (46630) are first-class — never remap to Sepolia or each other.
  if (chainId === CHAIN_ID_ROBINHOOD) return CHAIN_ID_ROBINHOOD
  if (chainId === CHAIN_ID_ROBINHOOD_TESTNET) return CHAIN_ID_ROBINHOOD_TESTNET

  if (chainId === CHAIN_ID_SEPOLIA) return CHAIN_ID_SEPOLIA
  if (chainId === CHAIN_ID_BASE_SEPOLIA) return CHAIN_ID_BASE_SEPOLIA

  if (chainId === CHAIN_ID_ANVIL || chainId === CHAIN_ID_LOCALHOST) {
    return preferredCanonicalChainId ?? CHAIN_ID_SEPOLIA
  }

  if (chainId === CHAIN_ID_BASE && isLocalSepoliaEnvironment(environment)) {
    return CHAIN_ID_BASE_SEPOLIA
  }

  return null
}

export function isSupportedChainId(chainId: number, environment: DeploymentEnvironment = defaultDeploymentEnvironment): boolean {
  const resolved = resolveArtifactsChainId(chainId, environment)
  if (resolved === null) return false
  if (resolved === CHAIN_ID_ROBINHOOD) {
    return (
      getArtifactBundle('anvil_robinhood_main', CHAIN_ID_ROBINHOOD) !== null ||
      getArtifactBundle(environment, CHAIN_ID_ROBINHOOD) !== null
    )
  }
  if (resolved === CHAIN_ID_ROBINHOOD_TESTNET) {
    return (
      getArtifactBundle('anvil_robinhood_testnet', CHAIN_ID_ROBINHOOD_TESTNET) !== null ||
      getArtifactBundle(environment, CHAIN_ID_ROBINHOOD_TESTNET) !== null
    )
  }
  return getArtifactBundle(environment, resolved) !== null
}

export function getAddressArtifacts(
  chainId: number,
  environment: DeploymentEnvironment = defaultDeploymentEnvironment
): AddressArtifacts {
  const resolved = resolveArtifactsChainId(chainId, environment)
  if (resolved === null) {
    throw new Error(
      `Unsupported chainId ${chainId}. Supported: ${CHAIN_ID_SEPOLIA} (Sepolia), ${CHAIN_ID_BASE_SEPOLIA} (Base Sepolia), ${CHAIN_ID_ROBINHOOD} (Robinhood), ${CHAIN_ID_ROBINHOOD_TESTNET} (Robinhood Testnet / Anvil 46630).`
    )
  }

  // Prefer dedicated Anvil registries for RH mainnet (4663) and testnet (46630).
  const bundle =
    resolved === CHAIN_ID_ROBINHOOD
      ? (getArtifactBundle('anvil_robinhood_main', CHAIN_ID_ROBINHOOD) ??
        getArtifactBundle(environment, CHAIN_ID_ROBINHOOD))
      : resolved === CHAIN_ID_ROBINHOOD_TESTNET
        ? (getArtifactBundle('anvil_robinhood_testnet', CHAIN_ID_ROBINHOOD_TESTNET) ??
          getArtifactBundle(environment, CHAIN_ID_ROBINHOOD_TESTNET))
        : getArtifactBundle(environment, resolved)

  if (!bundle) {
    throw new Error(`No deployment bundle is registered for environment ${environment} on chain ${resolved}.`)
  }

  // Prefer the chain-keyed platform override when available. Each next deploy
  // to a chain refreshes chain/<chainId>/platform.json so the latest deploy
  // wins regardless of which legacy env the rest of the bundle belongs to.
  const override = CHAIN_PLATFORM_OVERRIDES[resolved]
  if (override && typeof override === 'object') {
    return { ...bundle, platform: override }
  }

  return bundle
}
