import type { TokenListRef } from './tokenlistCompose'
import { GENERATED_LIST_REGISTRY } from './tokenlistRegistry.generated'

/**
 * Token Lists indexed by chain id. The registry is generated by the aggregator
 * (`cd scripts/node && npm run build-tokenlists`) from whatever it finds under
 * frontend/app/addresses/chain/<chainId>/. Adding a new chain only requires
 * dropping its tokenlist files into a new chain/<id>/ directory and re-running
 * the aggregator.
 */
export const LIST_REGISTRY: Record<number, TokenListRef[]> = GENERATED_LIST_REGISTRY

export function getListRefs(chainId: number): TokenListRef[] {
  return LIST_REGISTRY[chainId] ?? []
}
