import { promises as fs } from 'node:fs'
import { join, relative, resolve } from 'node:path'

const GENERATED_BANNER =
  '// AUTO-GENERATED by scripts/node/build-tokenlists. Do not edit by hand.\n' +
  '// Run `cd scripts/node && npm run build-tokenlists` to regenerate after adding\n' +
  '// or removing tokenlist files under frontend/app/addresses/chain/.\n'

const RELATIVE_LIB_DIR = 'frontend/app/lib'
const RELATIVE_CHAIN_DIR = 'frontend/app/addresses/chain'

interface ChainEntry {
  chainId: number
  buckets: { id: string; identifier: string; importPath: string }[]
  platformImportPath: string | null
  platformIdentifier: string | null
}

function toCamelCase(input: string): string {
  return input
    .split(/[^a-zA-Z0-9]+/)
    .filter((part) => part.length > 0)
    .map((part, index) =>
      index === 0 ? part.charAt(0).toLowerCase() + part.slice(1) : part.charAt(0).toUpperCase() + part.slice(1)
    )
    .join('')
}

async function readChainIds(chainDir: string): Promise<number[]> {
  let entries: { name: string; isDirectory: () => boolean }[]
  try {
    entries = await fs.readdir(chainDir, { withFileTypes: true })
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') return []
    throw err
  }
  const ids: number[] = []
  for (const entry of entries) {
    if (!entry.isDirectory()) continue
    const parsed = Number(entry.name)
    if (!Number.isFinite(parsed) || !Number.isInteger(parsed) || parsed <= 0) continue
    if (String(parsed) !== entry.name) continue
    ids.push(parsed)
  }
  return ids.sort((a, b) => a - b)
}

async function collectChainEntry(chainDir: string, chainId: number): Promise<ChainEntry | null> {
  const dir = join(chainDir, String(chainId))
  const files = await fs.readdir(dir)

  const buckets = files
    .filter((f) => f.endsWith('.tokenlist.json'))
    .map((f) => f.slice(0, -'.tokenlist.json'.length))
    .sort()
    .map((id) => ({
      id,
      identifier: `chain${chainId}_${toCamelCase(id)}`,
      importPath: `../addresses/chain/${chainId}/${id}.tokenlist.json`,
    }))

  const hasPlatform = files.includes('platform.json')
  const platformImportPath = hasPlatform ? `../addresses/chain/${chainId}/platform.json` : null
  const platformIdentifier = hasPlatform ? `chain${chainId}_platform` : null

  if (buckets.length === 0 && !hasPlatform) return null

  return { chainId, buckets, platformImportPath, platformIdentifier }
}

function renderTokenlistRegistry(entries: ChainEntry[]): string {
  const lines: string[] = []
  lines.push(GENERATED_BANNER)
  lines.push(`import type { TokenList, TokenListRef } from './tokenlistCompose'\n`)

  for (const entry of entries) {
    if (entry.buckets.length === 0) continue
    lines.push(`// Chain ${entry.chainId}`)
    for (const bucket of entry.buckets) {
      lines.push(`import ${bucket.identifier} from '${bucket.importPath}'`)
    }
    lines.push('')
  }

  lines.push(
    `const ref = (id: string, list: unknown, priority = 50): TokenListRef => ({ id, priority, list: list as TokenList })\n`
  )

  lines.push('export const GENERATED_LIST_REGISTRY: Record<number, TokenListRef[]> = {')
  for (const entry of entries) {
    if (entry.buckets.length === 0) continue
    lines.push(`  ${entry.chainId}: [`)
    for (const bucket of entry.buckets) {
      lines.push(`    ref('${bucket.id}', ${bucket.identifier}),`)
    }
    lines.push('  ],')
  }
  lines.push('}')
  lines.push('')

  return lines.join('\n')
}

function renderPlatformOverrides(entries: ChainEntry[]): string {
  const platformEntries = entries.filter((e) => e.platformImportPath !== null)

  const lines: string[] = []
  lines.push(GENERATED_BANNER)

  for (const entry of platformEntries) {
    lines.push(`import ${entry.platformIdentifier} from '${entry.platformImportPath}'`)
  }
  if (platformEntries.length > 0) lines.push('')

  lines.push('export const GENERATED_CHAIN_PLATFORM_OVERRIDES: Record<number, unknown> = {')
  for (const entry of platformEntries) {
    lines.push(`  ${entry.chainId}: ${entry.platformIdentifier},`)
  }
  lines.push('}')
  lines.push('')

  return lines.join('\n')
}

export interface GenerateRegistryResult {
  registryPath: string
  overridesPath: string
  chainIds: number[]
}

export async function generateRegistryFiles(repoRoot: string): Promise<GenerateRegistryResult> {
  const chainDir = resolve(repoRoot, RELATIVE_CHAIN_DIR)
  const libDir = resolve(repoRoot, RELATIVE_LIB_DIR)

  const chainIds = await readChainIds(chainDir)
  const entries: ChainEntry[] = []
  for (const id of chainIds) {
    const entry = await collectChainEntry(chainDir, id)
    if (entry) entries.push(entry)
  }

  const registryPath = join(libDir, 'tokenlistRegistry.generated.ts')
  const overridesPath = join(libDir, 'chainPlatformOverrides.generated.ts')

  await fs.mkdir(libDir, { recursive: true })
  await fs.writeFile(registryPath, renderTokenlistRegistry(entries))
  await fs.writeFile(overridesPath, renderPlatformOverrides(entries))

  return {
    registryPath: relative(repoRoot, registryPath),
    overridesPath: relative(repoRoot, overridesPath),
    chainIds: entries.map((e) => e.chainId),
  }
}
